### ISSUE TITLE
Fatal error trying to decode unknown error detail formats

### ISSUE THREAD

**Issue by perariontaeadastra** [stackpath/stackpath-wordpress#1] opened 2020-04-24 22:25 UTC
Hi.

I've just installed this plugin on 2 websites, and on one of them it causes an issue.
7772#0: *2010 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Object of class stdClass could not be converted to string in /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/stackpath-wordpress/src/Exception/API/RequestException.php:167
Stack trace:
#0 /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/stackpath-wordpress/src/Exception/API/RequestException.php(167): implode()
#1 /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/stackpath-wordpress/src/WordPress/Message.php(50): StackPath\Exception\API\RequestException->detailedErrorMessage()
#2 /var/www/vhosts/domain.com/httpdocs/wp-content/plugins/stackpath-wordpress/src/WordPress/Plugin/PostActions.php(222): StackPath\WordPress\Message::fromException()
#3 /var/www/vhosts/domain.com/httpdocs/wp-includes/class-wp-hook.php(287): StackPath\WordPress\Plugin->bypassCacheOnWordPressCookieAction()
#4 /var/www/vhosts/domain.com/httpdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#5 /var/www/vhosts/domain.com/httpdocs/wp-includes/pl" while reading response header from upstream
That only happens when I hit save button for **Bypass Cache for WordPress Cookies**

**Comment by klaude** [comment] 2020-04-24 22:44
Howdy, @perariontaeadastra. Thanks for submitting this issue and for the stack trace! What version of WordPress and PHP are you using? 

Can you open a support ticket referencing this issue's URL (`https://github.com/stackpath/stackpath-wordpress/issues/1`) and the StackPath site you're running the plugin on? That's the most secure way to tell us which of your sites is experiencing the problem. I'll ask our support team to look out for it and to let me know when it comes in. Once I know which site this happens on I'll look through our API logs and see if I can duplicate the issue. 

Judging from the stack trace it looks like the plugin is receiving an API error with a structure that it wasn't expecting. That should be an easy fix once we find out which site this is happening on. Thank you very much!

**Comment by perariontaeadastra** [comment] 2020-04-24 22:58
Hi @klaude. 
Thank you for your prompt reply
I will create a ticket, no problem.

**Comment by perariontaeadastra** [comment] 2020-04-24 23:11
@klaude I am using:
WordPress version 5.4
PHP version 7.4.5

**Comment by klaude** [comment] 2020-04-24 23:32
Yo, thank you for using current versions of PHP and WordPress. Every admin should be so diligent! I got word of your support ticket. Thanks for doing that. I'll look into this and will have more information for you soon.

**Comment by perariontaeadastra** [comment] 2020-04-24 23:39
thank you.
I am glad I can help. This plugin is an essential one, so I will help as much as I can.

**Comment by klaude** [comment] 2020-04-25 05:51
Thanks for waiting! I see a few issues here:

1) The plugin doesn't have a way to show StackPath API error details. That makes troubleshooting these kinds of issues very difficult.
2) Over the past month or so we added a request ID field to API error message details. Folks from our support and development teams can look up your API request from that ID and trace the cause of the error. The plugin is expecting all error details to come in as strings, but this request ID comes in as part of an object. That's what's making the fatal error.
3) There's an issue with your StackPath site that prevents setting the configuration bit to bypass cache on the common WordPress cookies. 

That call to StackPath returns an error that the plugin can't parse. Then it's difficult to troubleshoot since there's no real debugging in place short of editing code. 

I've got way better debug display and logging that honors WordPress's `WP_DEBUG`, `WP_DEBUG_DISPLAY`, and `WP_DEBUG_LOG` settings in a branch in my fork. I've almost got error handling figured out too and will have a pull request for these in this weekend. In the meantime to get your service up and running I've relayed the error that I'm seeing from your site to our support team. They should be able to get you up and running _tout de suite_. I hope this helps, and I'll shout out again when I have error handling buttoned down. Thanks!

**Comment by klaude** [comment] 2020-04-27 20:31
Eek, merging #2 closed this. I've got better error reporting merged into master and will cut a new release soon. This won't fix the issue with your StackPath service trying to enable the bypass cache setting, but it will make it far easier to spot.

**Comment by klaude** [comment] 2020-04-27 20:54
@perariontaeadastra, please back up your StackPath plugin and give this one a try in its place: https://github.com/stackpath/stackpath-wordpress/releases/download/v0.2.0/stackpath-wordpress-v0.2.0.zip . Let us know how this works for you. This should fix the fatal error and get you more information to go with when you're working with our support team.

**Comment by perariontaeadastra** [comment] 2020-04-27 20:57
@klaude ok, no problem. Will give it a try

**Comment by perariontaeadastra** [comment] 2020-04-27 21:35
@klaude I am getting this:
Unable to set bypass cache at StackPath
Validation Failure: Domain contains a hash that does not match this host

**Comment by klaude** [comment] 2020-04-27 23:29
Hey, that's progress at least. I'm afraid that error is coming from the StackPath API due to an issue in your site's configuration. I don't think we can fix this one in the plugin, but I can bump your issue with our support team. Can you email me your support ticket ID? I'll bump it up with our team. I'm at kevin.laude@stackpath.com. Thanks!

**Comment by perariontaeadastra** [comment] 2020-04-29 15:47
After that back-end issue was corrected, plugin itself works fine now!
Thanks you for your help!

**Comment by klaude** [comment] 2020-04-29 18:02
Hey that's great! I'm glad it's working now. I'm going to close this issue out. Please open another if you spot any other plugin issues. Thanks!

**Closed by klaude** 2020-04-29 18:02 UTC
